# Generated by Django 4.1.7 on 2023-07-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('publish', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=50)),
                ('Sid', models.IntegerField(default=0)),
                ('Bname', models.CharField(max_length=50)),
                ('Bid', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('expiry', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Issue',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('post_content', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('plan', models.CharField(max_length=20)),
                ('Duration', models.DurationField(default='SOME STRING')),
            ],
            options={
                'db_table': 'Sub',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
                ('bname', models.CharField(default=0, max_length=50)),
                ('subscrib', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.sub')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Replie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('reply_content', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.post')),
            ],
            options={
                'db_table': 'Replie',
            },
        ),
    ]
