# Generated by Django 4.1.7 on 2023-07-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_student_subscrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
