# Generated by Django 4.1.7 on 2023-07-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_replie_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.post'),
        ),
    ]
