# Generated by Django 4.1.7 on 2023-07-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_replie_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='Duration',
            field=models.DurationField(),
        ),
    ]
